[scripts] error handling in pac url script

diff --git a/scripts/.local/bin/pacurl b/scripts/.local/bin/pacurl
--- a/scripts/.local/bin/pacurl
+++ b/scripts/.local/bin/pacurl
@@ -1,3 +1,8 @@
 #!/bin/bash
 
-xdg-open "$(expac -S %u "$1")";
+if ! url=$(expac -S %u "$1"); then
+    printf "Could not resolve url for %s.\n" "$1"
+    exit 1
+fi
+
+xdg-open "$url";
